controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

weather_highlander_says:
    path: /weather/highlander-says
    controller: App\Controller\WeatherController::highlanderSays
